# This is a basic workflow to help you get started with Actions

name: Helm Chart Prerelease

# Controls when the action will run. 
on:
  release:
    types: [prereleased]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Create the Helm Chart 
        run: |
          rm -rf .helm-prerelease
          mkdir .helm-prerelease
          helm package -u charts/eap74 -d .helm-prerelease
     
      - name: Upload the generated archive
        uses: 'actions/upload-artifact@v3'
        with:
          path: .helm-prerelease/**